[development]
port = 8000

[development.databases]
postgres = { url = "postgres://rocket:rocket@localhost/rocket" }

[staging]
port = 80

[staging.databases]
postgres = { url = "postgres://rocket:rocket@localhost/rocket" }